[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure WebAssembly files are served with correct MIME type
[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Resource-Policy = "cross-origin"

# Ensure Python files are served correctly
[[headers]]
  for = "*.py"
  [headers.values]
    Content-Type = "text/plain"
    Cross-Origin-Resource-Policy = "cross-origin"
